#!/usr/bin/env python3

from persistqueue import FIFOSQLiteQueue
import feedparser
import json
import logging
import logging
import os
import re
import requests
import sys
import telebot
import threading
import time
import yt_dlp


def download():

    while True:
        items = q.get()
        url = items.pop(0)
        if items:
            message = items.pop(0)

        logging.info(f"download    : processing {url}")
        ydl_opts = {
            "download_archive": "/config/download-archive",
            "ignoreerrors": True,
            "writesubtitles": True,
            "writeautomaticsub": True,
            "subtitleslangs": ["sv.*", "en.*"],
            "writethumbnail": True,
            "outtmpl": "/data/%(uploader)s/%(timestamp)s/S01E%(upload_date)s - %(uploader)s - %(title)s [%(id)s].%(ext)s",
            # "verbose": True,
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            info = ydl.sanitize_info(info)
            if info:
                text = "Hemladdat 📼🏴‍☠️"
                if message:
                    bot.reply_to(message, text)
                else:
                    bot.send_message(CHAT_ID, f"{text}: {url}")
            else:
                if message:
                    text = "Troligen nerladdat tidigare 🤷‍♂️"
                    bot.reply_to(message, text)

        q.task_done()


def rss():
    while True:
        logging.info("RSS    : starting to fetch feeds")
        channels = open("/config/channel-file", "r")
        for channel in channels:
            logging.info(f"RSS    : processing {channel}")
            url = f"https://www.youtube.com/feeds/videos.xml?channel_id={channel}"
            try:
                feed = feedparser.parse(url)
            except:
                logging.info(f"rss    : feed error")
                time.sleep(30)
                continue

            for post in feed.entries:
                q.put([post.link])

            time.sleep(30)

        channels.close

        logging.info("RSS    : sleeping for one hour")
        time.sleep(3600)


def telegram():
    logging.info(f"telegram    : Starting telegram bot")

    @bot.message_handler(commands=["start", "help"])
    def send_welcome(message):
        bot.reply_to(
            message, f"Configure the following ID server-side: {message.chat.id}"
        )

    @bot.message_handler(regexp="^(https?://[^\s]+)")
    def handle_http_message(message):
        if message.chat.id != CHAT_ID:
            logging.info(f"telegram    : discarding message from {message.chat.id}")
            return

        url = message.text
        q.put([url, message])
        logging.info(f"telegram    : processing message with url: {url}")
        reply_text = "Köat 👍"
        bot.reply_to(message, reply_text)

    @bot.message_handler(func=lambda message: True)
    def catch_all(message):
        logging.info(f"telegram    : discarding message with invalid message")
        bot.reply_to(message, message.text)

    bot.infinity_polling()


if __name__ == "__main__":
    format = "%(asctime)s: %(message)s"
    logging.basicConfig(format=format, level=logging.INFO, datefmt="%H:%M:%S")

    CHAT_ID = int(os.environ["CHAT_ID"])
    TOKEN = os.environ["TOKEN"]

    bot = telebot.TeleBot(TOKEN, parse_mode=None)
    q = FIFOSQLiteQueue(path="/config/queue", multithreading=True, auto_commit=False)

    x = threading.Thread(target=rss)
    y = threading.Thread(target=telegram)
    z = threading.Thread(target=download)

    x.start()
    y.start()
    z.start()

# For testing
# URL = "https://www.youtube.com/watch?v=BaW_jenozKc"
# URL = 'https://www.youtube.com/watch?v=PEHoaB6X3cs'
# URL = 'https://vimeo.com/731378604'

# download(URL)
